title: Something
author: Tran Minh Sang
email: sangtran.d14ptit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Something

# social links
github_username:  sangtm-04

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
